language: node_js
node_js:
  - "stable"

script: 
  - npm install  
  - npm run build

install: 
  - npm install -g firebase-tools

after_success:     
  - firebase deploy --token $FIREBASE_TOKEN

on:
  branch: master